config/routes.rb
Rails.application.routes.draw do

  mount ActionCable.server => '/cable'

  scope :message do
    get '/list',    to: 'messages#list'
    post '/create', to: 'messages#create'
  end

  devise_for :people
  get 'chat', to: 'pages#chat'

  root to: 'pages#landing'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :person

  def display
    "(#{self.created_at}) #{self.person.email}: #{self.content}"
  end

  def append
    self.display.prepend('<li>').concat('</li>')
  end
end

app/models/person.rb
class Person < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  
  def create
    person, content = params[:person_id], params[:content]
    puts [person,content]
    message = Message.create(person_id: person, content: content)
    update_message_list(message.append)
    head :ok
  end

  def update_message_list(message)
    ActionCable.server.broadcast("jchat_channel", message)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def landing
    redirect_to action: 'chat' if current_person
  end

  def chat
    redirect_to action: 'landing' if !current_person
    @messages = Message.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_auth_links.haml
%header
  - if current_person
    = "Hi #{current_person.email}"
    = link_to 'Sign out', destroy_person_session_path, method: :delete
  - else
    = link_to 'Signup', new_person_registration_path
    = link_to 'Login', new_person_session_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Jchat
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render '/layouts/auth_links'
    = yield

app/views/pages/chat.html.haml
#main
  %section#messages
    %ul#message_list
      - @messages.each do |m|
        %li
          = m.display

  %section#message_input
    = form_tag '/message/create', remote: true do
      = hidden_field_tag 'person_id', current_person.id
      = text_area_tag 'content'
      = submit_tag 'Send'